<a href="https://colab.research.google.com/github/Mtigno14/Linear-Algebra-58019/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Python program to inverse

In [21]:
import numpy as np
A = np.array([[1,2],[4,7]])
B = np.linalg.inv(A)
print(B)

C = np.dot(A,B)
print(C)

[[-7.  2.]
 [ 4. -1.]]
[[1. 0.]
 [0. 1.]]


In [30]:
##Python Program to inverse a 3x3 Matrix

A = np.array([[6,1,1],[4,-2,5],[2,8,7]]) #original components
print(A)
B = np.linalg.inv(A)
print("\nThe inverse above is: ")
print(B)
C = np.transpose(A)
print("\ntransposed as: ")
print(C)

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]

The inverse above is: 
[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]

transposed as: 
[[ 6  4  2]
 [ 1 -2  8]
 [ 1  5  7]]


## Program Code Product of A and B

In [39]:
D = np.cross(A, B)
print(D)

[[-0.01960784  0.31372549 -0.19607843]
 [ 0.48366013 -0.04575163 -0.40522876]
 [-0.63398693 -0.92810458  1.24183007]]
