<a href="https://colab.research.google.com/github/Mtigno14/Linear-Algebra-58019/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Practical Lab Exam 1

##Problem 1

In [3]:
import numpy as np

title = "Problem 1: \n"
print(title)

A = np.matrix ([[1,2,3],[4,5,6]])
B = np.matrix (([1,2],[3,4],[5,6]))
C = np.array ([[1,2,3],[4,5,6],[7,8,9]])
D = np.array (([1,2],[3,4]))

multiplication = A * B
print("a.")
print(multiplication,"\n")


sum = D + D
print("b.")
print(sum,"\n")

print("c.")
print(2*C)

Problem 1: 

a.
[[22 28]
 [49 64]] 

b.
[[2 4]
 [6 8]] 

c.
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


##Problem 2

In [2]:
import numpy as np

print("Problem 2: \n")
X = np.array([5, 3, -1])

print("\nType:")
print(type(X))
print("\nShape:")
print(X.shape) #shape
print("\nDimension:")
print(X.ndim)  #dimension
print("\nSize:")
print(X.size)

Problem 2: 


Type:
<class 'numpy.ndarray'>

Shape:
(3,)

Dimension:
1

Size:
3
